import React, { useState, useMemo } from 'react'
import { useApp } from '../context/AppContext'
import { FileText, Download, Calendar, TrendingUp, TrendingDown, BarChart2 } from 'lucide-react'

const fmtFull = n => `₹${Number(n).toLocaleString('en-IN')}`

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
const MONTHS_HI = ['जन','फर','मार','अप्र','मई','जून','जुल','अग','सित','अक्त','नव','दिस']

function generateReportHTML(title, tableHTML, summaryHTML, business, period) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"/>
<title>${title}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',Arial,sans-serif;color:#1f2937;background:white}
.page{max-width:800px;margin:0 auto;padding:32px}
.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:28px;padding-bottom:20px;border-bottom:3px solid #1E3A5F}
.biz-name{font-size:22px;font-weight:800;color:#1E3A5F}
.report-title{font-size:24px;font-weight:800;color:#F97316;text-align:right}
.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px}
.sum-card{background:#f9fafb;border-radius:10px;padding:14px;border:1px solid #e5e7eb;text-align:center}
.sum-label{font-size:11px;color:#9ca3af;margin-bottom:6px;text-transform:uppercase}
.sum-value{font-size:20px;font-weight:800;color:#1E3A5F}
table{width:100%;border-collapse:collapse}
thead tr{background:#1E3A5F;color:white}
thead th{padding:11px 14px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase}
tbody tr:nth-child(even){background:#f9fafb}
tbody td{padding:10px 14px;font-size:13px;border-bottom:1px solid #f3f4f6}
.total-row td{font-weight:700;background:#EFF6FF;font-size:14px}
.btn{background:#F97316;color:white;border:none;padding:10px 20px;border-radius:8px;cursor:pointer;font-size:14px;font-weight:700;margin-right:8px}
.footer{margin-top:24px;text-align:center;font-size:11px;color:#d1d5db;padding-top:16px;border-top:1px solid #e5e7eb}
@media print{.no-print{display:none}}
</style></head><body>
<div class="page">
<div class="no-print" style="text-align:right;margin-bottom:20px">
<button class="btn" onclick="window.print()">🖨️ Print / Save PDF</button>
<button onclick="window.close()" style="background:#f3f4f6;border:none;padding:10px 16px;border-radius:8px;cursor:pointer">✕ Close</button>
</div>
<div class="header">
<div>
<div class="biz-name">${business?.name || 'Business'}</div>
<div style="font-size:12px;color:#6b7280;margin-top:4px">${business?.address || ''}</div>
${business?.gstin ? `<div style="font-size:12px;color:#6b7280">GSTIN: ${business.gstin}</div>` : ''}
</div>
<div>
<div class="report-title">${title}</div>
<div style="font-size:13px;color:#6b7280;text-align:right;margin-top:4px">Period: ${period}</div>
<div style="font-size:12px;color:#9ca3af;text-align:right">Generated: ${new Date().toLocaleString('en-IN')}</div>
</div>
</div>
${summaryHTML}
${tableHTML}
<div class="footer">Generated by HisaabPro — Smart Vyapar Ledger · hisaabpro.app</div>
</div></body></html>`
}

export default function GSTReportsScreen() {
  const { transactions, invoices, parties, business, products, stats, language } = useApp()
  const hi = language === 'hi'

  const currentYear = new Date().getFullYear()
  const currentMonth = new Date().getMonth()

  const [reportType, setReportType] = useState('monthly') // monthly | yearly | gst | pl
  const [selectedMonth, setSelectedMonth] = useState(currentMonth)
  const [selectedYear, setSelectedYear] = useState(currentYear)

  const years = [currentYear, currentYear - 1, currentYear - 2]

  // ── Filter transactions by period ────────────────────────────────────────
  const filteredTxns = useMemo(() => {
    return transactions.filter(t => {
      const d = new Date(t.date)
      if (reportType === 'monthly') return d.getMonth() === selectedMonth && d.getFullYear() === selectedYear
      if (reportType === 'yearly') return d.getFullYear() === selectedYear
      if (reportType === 'gst') return d.getMonth() === selectedMonth && d.getFullYear() === selectedYear
      if (reportType === 'pl') return d.getFullYear() === selectedYear
      return true
    })
  }, [transactions, reportType, selectedMonth, selectedYear])

  const filteredInvoices = useMemo(() => {
    return (invoices || []).filter(inv => {
      const d = new Date(inv.date)
      if (reportType === 'monthly' || reportType === 'gst') return d.getMonth() === selectedMonth && d.getFullYear() === selectedYear
      return d.getFullYear() === selectedYear
    })
  }, [invoices, reportType, selectedMonth, selectedYear])

  const totalSales = filteredTxns.filter(t => t.type === 'sale').reduce((s, t) => s + t.amount, 0)
  const totalPurchases = filteredTxns.filter(t => t.type === 'purchase').reduce((s, t) => s + t.amount, 0)
  const totalReceipts = filteredTxns.filter(t => t.type === 'receipt').reduce((s, t) => s + t.amount, 0)
  const totalPayments = filteredTxns.filter(t => t.type === 'payment').reduce((s, t) => s + t.amount, 0)
  const grossProfit = totalSales - totalPurchases
  const gstRate = business?.gstEnabled !== false ? (business?.gstRate || 5) : 0
  const totalGSTCollected = filteredInvoices.reduce((s, i) => s + (i.taxAmount || 0), 0)
  const totalGSTPaid = Math.round(totalPurchases * gstRate / 100)
  const netGST = totalGSTCollected - totalGSTPaid

  const periodLabel = reportType === 'monthly' || reportType === 'gst'
    ? `${MONTHS[selectedMonth]} ${selectedYear}`
    : `FY ${selectedYear}-${String(selectedYear + 1).slice(2)}`

  // ── Monthly data for yearly view ─────────────────────────────────────────
  const monthlyData = MONTHS.map((m, idx) => {
    const txns = transactions.filter(t => {
      const d = new Date(t.date)
      return d.getMonth() === idx && d.getFullYear() === selectedYear
    })
    const sales = txns.filter(t => t.type === 'sale').reduce((s, t) => s + t.amount, 0)
    const purchases = txns.filter(t => t.type === 'purchase').reduce((s, t) => s + t.amount, 0)
    const receipts = txns.filter(t => t.type === 'receipt').reduce((s, t) => s + t.amount, 0)
    const invs = (invoices || []).filter(i => { const d = new Date(i.date); return d.getMonth() === idx && d.getFullYear() === selectedYear })
    const gst = invs.reduce((s, i) => s + (i.taxAmount || 0), 0)
    return { month: m, sales, purchases, receipts, profit: sales - purchases, gst }
  })

  // ── PDF Generation ────────────────────────────────────────────────────────
  const handlePDF = () => {
    let tableHTML = '', summaryHTML = ''

    if (reportType === 'monthly' || reportType === 'pl') {
      summaryHTML = `<div class="summary">
        <div class="sum-card"><div class="sum-label">Total Sales</div><div class="sum-value" style="color:#059669">${fmtFull(totalSales)}</div></div>
        <div class="sum-card"><div class="sum-label">Total Purchases</div><div class="sum-value" style="color:#DC2626">${fmtFull(totalPurchases)}</div></div>
        <div class="sum-card"><div class="sum-label">Cash Received</div><div class="sum-value" style="color:#2563EB">${fmtFull(totalReceipts)}</div></div>
        <div class="sum-card"><div class="sum-label">Gross Profit</div><div class="sum-value" style="color:${grossProfit >= 0 ? '#059669' : '#DC2626'}">${fmtFull(grossProfit)}</div></div>
      </div>`
      const rows = filteredTxns.map(t => {
        const party = parties.find(p => p.id === t.partyId)
        const isIncoming = t.type === 'sale' || t.type === 'receipt'
        return `<tr><td>${t.date}</td><td>${party?.name || '—'}</td><td><span style="background:${isIncoming?'#D1FAE5':'#FEE2E2'};padding:2px 8px;border-radius:99px;font-size:11px;font-weight:600;color:${isIncoming?'#059669':'#DC2626'}">${t.type}</span></td><td style="text-align:right;color:${isIncoming?'#059669':'#DC2626'};font-weight:600">${isIncoming?'+':'-'}${fmtFull(t.amount)}</td><td>${t.note||'—'}</td><td>${t.billNo||'—'}</td></tr>`
      }).join('')
      tableHTML = `<table><thead><tr><th>Date</th><th>Party</th><th>Type</th><th style="text-align:right">Amount</th><th>Note</th><th>Bill No</th></tr></thead><tbody>${rows}<tr class="total-row"><td colspan="3"><strong>TOTAL</strong></td><td style="text-align:right;color:#059669">+${fmtFull(totalSales+totalReceipts)}</td><td colspan="2"></td></tr></tbody></table>`
    }

    if (reportType === 'gst') {
      summaryHTML = `<div class="summary">
        <div class="sum-card"><div class="sum-label">GST Collected (Sales)</div><div class="sum-value" style="color:#DC2626">${fmtFull(totalGSTCollected)}</div></div>
        <div class="sum-card"><div class="sum-label">GST Paid (Purchase)</div><div class="sum-value" style="color:#059669">${fmtFull(totalGSTPaid)}</div></div>
        <div class="sum-card"><div class="sum-label">Net GST Payable</div><div class="sum-value" style="color:${netGST>=0?'#DC2626':'#059669'}">${fmtFull(Math.abs(netGST))}</div></div>
        <div class="sum-card"><div class="sum-label">Total Invoices</div><div class="sum-value">${filteredInvoices.length}</div></div>
      </div>`
      const rows = filteredInvoices.map(inv => {
        const party = parties.find(p => p.id === inv.partyId)
        return `<tr><td>${inv.date}</td><td>${inv.invoiceNo}</td><td>${party?.name||'—'}</td><td style="text-align:right">${fmtFull(inv.subtotal)}</td><td style="text-align:right">${fmtFull(inv.discount||0)}</td><td style="text-align:right;color:#DC2626;font-weight:600">${fmtFull(inv.taxAmount||0)}</td><td style="text-align:right;font-weight:700">${fmtFull(inv.totalAmount)}</td><td><span style="background:${inv.status==='paid'?'#D1FAE5':inv.status==='partial'?'#FEF3C7':'#FEE2E2'};padding:2px 8px;border-radius:99px;font-size:11px;font-weight:600">${inv.status}</span></td></tr>`
      }).join('')
      tableHTML = `<table><thead><tr><th>Date</th><th>Invoice No</th><th>Party</th><th style="text-align:right">Subtotal</th><th style="text-align:right">Discount</th><th style="text-align:right">GST (${gstRate}%)</th><th style="text-align:right">Total</th><th>Status</th></tr></thead><tbody>${rows}<tr class="total-row"><td colspan="5"><strong>TOTAL</strong></td><td style="text-align:right;color:#DC2626"><strong>${fmtFull(totalGSTCollected)}</strong></td><td style="text-align:right"><strong>${fmtFull(filteredInvoices.reduce((s,i)=>s+i.totalAmount,0))}</strong></td><td></td></tr></tbody></table>`
    }

    if (reportType === 'yearly') {
      summaryHTML = `<div class="summary">
        <div class="sum-card"><div class="sum-label">Total Sales</div><div class="sum-value" style="color:#059669">${fmtFull(monthlyData.reduce((s,m)=>s+m.sales,0))}</div></div>
        <div class="sum-card"><div class="sum-label">Total Purchases</div><div class="sum-value" style="color:#DC2626">${fmtFull(monthlyData.reduce((s,m)=>s+m.purchases,0))}</div></div>
        <div class="sum-card"><div class="sum-label">Total GST</div><div class="sum-value" style="color:#D97706">${fmtFull(monthlyData.reduce((s,m)=>s+m.gst,0))}</div></div>
        <div class="sum-card"><div class="sum-label">Annual Profit</div><div class="sum-value" style="color:#2563EB">${fmtFull(monthlyData.reduce((s,m)=>s+m.profit,0))}</div></div>
      </div>`
      const rows = monthlyData.map(m => `<tr><td><strong>${m.month}</strong></td><td style="text-align:right;color:#059669">${fmtFull(m.sales)}</td><td style="text-align:right;color:#DC2626">${fmtFull(m.purchases)}</td><td style="text-align:right;color:#D97706">${fmtFull(m.gst)}</td><td style="text-align:right;color:#2563EB">${fmtFull(m.receipts)}</td><td style="text-align:right;font-weight:700;color:${m.profit>=0?'#059669':'#DC2626'}">${fmtFull(m.profit)}</td></tr>`).join('')
      const totals = monthlyData.reduce((acc, m) => ({ sales: acc.sales+m.sales, purchases: acc.purchases+m.purchases, gst: acc.gst+m.gst, receipts: acc.receipts+m.receipts, profit: acc.profit+m.profit }), { sales:0,purchases:0,gst:0,receipts:0,profit:0 })
      tableHTML = `<table><thead><tr><th>Month</th><th style="text-align:right">Sales</th><th style="text-align:right">Purchases</th><th style="text-align:right">GST Collected</th><th style="text-align:right">Cash Received</th><th style="text-align:right">Profit</th></tr></thead><tbody>${rows}<tr class="total-row"><td><strong>ANNUAL TOTAL</strong></td><td style="text-align:right;color:#059669"><strong>${fmtFull(totals.sales)}</strong></td><td style="text-align:right;color:#DC2626"><strong>${fmtFull(totals.purchases)}</strong></td><td style="text-align:right;color:#D97706"><strong>${fmtFull(totals.gst)}</strong></td><td style="text-align:right"><strong>${fmtFull(totals.receipts)}</strong></td><td style="text-align:right;color:${totals.profit>=0?'#059669':'#DC2626'}"><strong>${fmtFull(totals.profit)}</strong></td></tr></tbody></table>`
    }

    const titles = { monthly: 'Monthly Report', yearly: 'Annual Report', gst: 'GST Report', pl: 'P&L Statement' }
    const html = generateReportHTML(titles[reportType], tableHTML, summaryHTML, business, periodLabel)
    const win = window.open('', '_blank', 'width=900,height=700')
    win.document.write(html)
    win.document.close()
  }

  const reportTabs = [
    { id: 'monthly', label: 'Monthly', labelHi: 'मासिक', emoji: '📅' },
    { id: 'yearly',  label: 'Yearly',  labelHi: 'वार्षिक', emoji: '📊' },
    { id: 'gst',     label: 'GST',     labelHi: 'GST', emoji: '🧾' },
    { id: 'pl',      label: 'P&L',     labelHi: 'P&L', emoji: '📈' },
  ]

  return (
    <div style={{ paddingBottom: 80 }}>
      {/* Header */}
      <div style={{ background: 'linear-gradient(135deg, var(--indigo), var(--indigo-mid))', padding: '24px 16px 20px', borderRadius: '0 0 24px 24px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <div>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 700, color: 'white' }}>
              {hi ? 'बिज़नेस रिपोर्ट' : 'Business Reports'}
            </h2>
            <p style={{ color: 'rgba(255,255,255,0.65)', fontSize: 13, marginTop: 2 }}>{business?.name}</p>
          </div>
          <button onClick={handlePDF} style={{ background: 'var(--saffron)', border: 'none', borderRadius: 12, padding: '10px 14px', color: 'white', fontWeight: 700, fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6 }}>
            <Download size={15} /> PDF
          </button>
        </div>

        {/* Report Type Tabs */}
        <div style={{ display: 'flex', background: 'rgba(255,255,255,0.1)', borderRadius: 12, padding: 3, gap: 3 }}>
          {reportTabs.map(tab => (
            <button key={tab.id} onClick={() => setReportType(tab.id)} style={{
              flex: 1, padding: '9px 4px', borderRadius: 9, border: 'none', cursor: 'pointer',
              background: reportType === tab.id ? 'white' : 'transparent',
              color: reportType === tab.id ? 'var(--indigo)' : 'rgba(255,255,255,0.7)',
              fontWeight: 700, fontSize: 12, transition: 'all 0.2s',
            }}>{tab.emoji} {hi ? tab.labelHi : tab.label}</button>
          ))}
        </div>
      </div>

      <div style={{ padding: '16px 16px 0' }}>
        {/* Period Selector */}
        <div style={{ display: 'flex', gap: 10, marginBottom: 16, alignItems: 'center' }}>
          {(reportType === 'monthly' || reportType === 'gst' || reportType === 'pl') && (
            <select className="input-field" style={{ flex: 1 }} value={selectedMonth} onChange={e => setSelectedMonth(Number(e.target.value))}>
              {MONTHS.map((m, i) => <option key={i} value={i}>{m} {selectedYear}</option>)}
            </select>
          )}
          <select className="input-field" style={{ flex: 1 }} value={selectedYear} onChange={e => setSelectedYear(Number(e.target.value))}>
            {years.map(y => <option key={y} value={y}>{y}</option>)}
          </select>
        </div>

        {/* Summary Cards */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 }}>
          {reportType === 'gst' ? [
            { label: hi ? 'GST वसूला' : 'GST Collected', value: fmtFull(totalGSTCollected), color: 'var(--red)', bg: 'var(--red-light)' },
            { label: hi ? 'GST चुकाया' : 'GST Paid', value: fmtFull(totalGSTPaid), color: 'var(--green)', bg: 'var(--green-light)' },
            { label: hi ? 'देय GST' : 'Net GST Payable', value: fmtFull(Math.abs(netGST)), color: netGST >= 0 ? 'var(--red)' : 'var(--green)', bg: netGST >= 0 ? 'var(--red-light)' : 'var(--green-light)' },
            { label: hi ? 'कुल इनवॉइस' : 'Total Invoices', value: String(filteredInvoices.length), color: 'var(--indigo)', bg: 'var(--indigo-light)' },
          ].map((s, i) => (
            <div key={i} className="card" style={{ padding: 14, background: s.bg, border: 'none' }}>
              <div style={{ fontSize: 11, color: s.color, opacity: 0.8, marginBottom: 4 }}>{s.label}</div>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: 20, fontWeight: 800, color: s.color }}>{s.value}</div>
            </div>
          )) : [
            { label: hi ? 'कुल बिक्री' : 'Total Sales', value: fmtFull(totalSales), color: 'var(--green)', bg: 'var(--green-light)' },
            { label: hi ? 'कुल खरीद' : 'Total Purchases', value: fmtFull(totalPurchases), color: 'var(--red)', bg: 'var(--red-light)' },
            { label: hi ? 'भुगतान मिला' : 'Cash Received', value: fmtFull(totalReceipts), color: 'var(--indigo)', bg: 'var(--indigo-light)' },
            { label: hi ? 'मुनाफा' : 'Gross Profit', value: fmtFull(Math.abs(grossProfit)), color: grossProfit >= 0 ? 'var(--green)' : 'var(--red)', bg: grossProfit >= 0 ? 'var(--green-light)' : 'var(--red-light)' },
          ].map((s, i) => (
            <div key={i} className="card" style={{ padding: 14, background: s.bg, border: 'none' }}>
              <div style={{ fontSize: 11, color: s.color, opacity: 0.8, marginBottom: 4 }}>{s.label}</div>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: 20, fontWeight: 800, color: s.color }}>{s.value}</div>
            </div>
          ))}
        </div>

        {/* Yearly Monthly Breakdown */}
        {reportType === 'yearly' && (
          <div className="card" style={{ overflow: 'hidden', marginBottom: 16 }}>
            <div style={{ padding: '14px 16px', borderBottom: '1px solid var(--border-light)' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15, color: 'var(--indigo)' }}>
                📅 Month-wise Breakdown — {selectedYear}
              </h3>
            </div>
            {monthlyData.map((m, i) => m.sales > 0 || m.purchases > 0 ? (
              <div key={i} style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-light)', display: 'flex', alignItems: 'center', gap: 12 }}>
                <div style={{ width: 40, height: 40, borderRadius: 10, background: 'var(--indigo-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 12, color: 'var(--indigo)', flexShrink: 0 }}>
                  {hi ? MONTHS_HI[i] : m.month}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <span style={{ fontSize: 12, color: 'var(--green)', fontWeight: 600 }}>↑ {fmtFull(m.sales)}</span>
                    <span style={{ fontSize: 12, color: 'var(--red)', fontWeight: 600 }}>↓ {fmtFull(m.purchases)}</span>
                  </div>
                  <div style={{ height: 6, background: 'var(--border)', borderRadius: 99, overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${Math.min(100, (m.sales / Math.max(...monthlyData.map(x => x.sales), 1)) * 100)}%`, background: 'var(--green)', borderRadius: 99 }} />
                  </div>
                </div>
                <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 13, color: m.profit >= 0 ? 'var(--green)' : 'var(--red)', flexShrink: 0 }}>
                  {m.profit >= 0 ? '+' : ''}{fmtFull(m.profit)}
                </div>
              </div>
            ) : null)}
          </div>
        )}

        {/* GST Invoice List */}
        {reportType === 'gst' && (
          <div className="card" style={{ overflow: 'hidden', marginBottom: 16 }}>
            <div style={{ padding: '12px 16px 10px', borderBottom: '1px solid var(--border-light)' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 14, color: 'var(--indigo)' }}>
                Invoice-wise GST — {MONTHS[selectedMonth]} {selectedYear}
              </h3>
            </div>
            {filteredInvoices.length === 0 ? (
              <div style={{ padding: '30px 16px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>No invoices this period</div>
            ) : filteredInvoices.map((inv, i) => {
              const party = parties.find(p => p.id === inv.partyId)
              return (
                <div key={inv.id} style={{ padding: '11px 16px', borderBottom: i < filteredInvoices.length - 1 ? '1px solid var(--border-light)' : 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 13 }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{party?.name}</div>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{inv.invoiceNo} · {inv.date}</div>
                  </div>
                  <div style={{ textAlign: 'right', flexShrink: 0 }}>
                    <div style={{ fontWeight: 700, color: 'var(--red)', fontSize: 13 }}>GST: {fmtFull(inv.taxAmount || 0)}</div>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Total: {fmtFull(inv.totalAmount)}</div>
                  </div>
                </div>
              )
            })}
            <div style={{ padding: '12px 16px', background: 'var(--bg)', display: 'flex', justifyContent: 'space-between', fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 15 }}>
              <span style={{ color: 'var(--text-primary)' }}>Total GST Collected</span>
              <span style={{ color: 'var(--red)' }}>{fmtFull(totalGSTCollected)}</span>
            </div>
          </div>
        )}

        {/* P&L Transaction List */}
        {(reportType === 'monthly' || reportType === 'pl') && filteredTxns.length > 0 && (
          <div className="card" style={{ overflow: 'hidden', marginBottom: 16 }}>
            <div style={{ padding: '12px 16px 10px', borderBottom: '1px solid var(--border-light)' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 14, color: 'var(--indigo)' }}>
                {filteredTxns.length} Transactions — {periodLabel}
              </h3>
            </div>
            {filteredTxns.slice(0, 20).map((t, i) => {
              const party = parties.find(p => p.id === t.partyId)
              const isIn = t.type === 'sale' || t.type === 'receipt'
              return (
                <div key={t.id} style={{ padding: '10px 16px', borderBottom: i < Math.min(filteredTxns.length, 20) - 1 ? '1px solid var(--border-light)' : 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 13 }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{party?.name || '—'}</div>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{t.type} · {t.date}</div>
                  </div>
                  <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, color: isIn ? 'var(--green)' : 'var(--red)', flexShrink: 0 }}>
                    {isIn ? '+' : '-'}{fmtFull(t.amount)}
                  </div>
                </div>
              )
            })}
            {filteredTxns.length > 20 && <div style={{ padding: '10px 16px', textAlign: 'center', fontSize: 12, color: 'var(--text-muted)' }}>+{filteredTxns.length - 20} more — Download PDF for full list</div>}
          </div>
        )}

        {/* PDF Download CTA */}
        <div style={{ background: 'linear-gradient(135deg, var(--saffron-light), var(--indigo-light))', borderRadius: 14, padding: '16px', display: 'flex', alignItems: 'center', gap: 14 }}>
          <div style={{ fontSize: 32 }}>📄</div>
          <div style={{ flex: 1 }}>
            <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15, color: 'var(--indigo)', marginBottom: 3 }}>
              {hi ? 'PDF रिपोर्ट डाउनलोड करें' : 'Download PDF Report'}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
              {hi ? 'CA को share करें या print करें' : 'Share with CA or print for records'}
            </div>
          </div>
          <button onClick={handlePDF} style={{ background: 'var(--saffron)', border: 'none', borderRadius: 12, padding: '10px 14px', color: 'white', fontWeight: 700, fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
            <Download size={15} /> PDF
          </button>
        </div>
      </div>
    </div>
  )
}
