import React, { useState } from 'react'
import { useApp } from '../context/AppContext'
import { ArrowLeft, Phone, MessageCircle, Share2, TrendingUp, TrendingDown, Plus, FileText, Trash2, Edit2 } from 'lucide-react'
import { printInvoice } from '../utils/pdfGenerator'

const fmtFull = n => `₹${n.toLocaleString('en-IN')}`

// Generate party statement HTML
function generateStatementHTML(party, transactions, business) {
  const txns = transactions.filter(t => t.partyId === party.id).sort((a, b) => new Date(a.date) - new Date(b.date))
  const rows = txns.map((t, i) => {
    const isCredit = t.type === 'sale' || t.type === 'purchase'
    const isDebit = t.type === 'receipt' || t.type === 'payment'
    return `<tr style="border-bottom:1px solid #f3f4f6">
      <td style="padding:10px 14px;font-size:13px">${t.date}</td>
      <td style="padding:10px 14px;font-size:13px">${t.note || t.type} ${t.billNo ? `<br><span style="color:#9ca3af;font-size:11px">${t.billNo}</span>` : ''}</td>
      <td style="padding:10px 14px;text-align:right;font-size:13px;color:#16A34A;font-weight:700">${isCredit ? fmtFull(t.amount) : '-'}</td>
      <td style="padding:10px 14px;text-align:right;font-size:13px;color:#DC2626;font-weight:700">${isDebit ? fmtFull(t.amount) : '-'}</td>
      <td style="padding:10px 14px;text-align:right;font-size:13px;font-weight:700">${fmtFull(t.balanceAfter || 0)}</td>
    </tr>`
  }).join('')

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"/>
<title>Account Statement - ${party.name}</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',Arial,sans-serif;color:#1f2937;background:white}.page{max-width:750px;margin:0 auto;padding:32px}.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:20px;border-bottom:3px solid #1A1F5E}.business{font-size:24px;font-weight:800;color:#1A1F5E}.meta{text-align:right;font-size:13px;color:#6b7280}table{width:100%;border-collapse:collapse}thead tr{background:#1A1F5E;color:white}thead th{padding:11px 14px;text-align:left;font-size:12px;font-weight:600;text-transform:uppercase}.total-row{background:#f9fafb;font-weight:700}.btn{background:#FF6B1A;color:white;border:none;padding:10px 20px;border-radius:8px;cursor:pointer;font-size:14px;font-weight:700;margin-right:8px}@media print{.no-print{display:none}}</style>
</head><body><div class="page">
<div class="no-print" style="text-align:right;margin-bottom:20px">
<button class="btn" onclick="window.print()">🖨️ Print / PDF</button>
<button onclick="window.close()" style="background:#f3f4f6;border:none;padding:10px 16px;border-radius:8px;cursor:pointer">✕ Close</button>
</div>
<div class="header">
<div>
<div class="business">${business?.name || 'Business'}</div>
<div style="font-size:12px;color:#6b7280;margin-top:4px">${business?.address || ''} · ${business?.phone || ''}</div>
</div>
<div class="meta">
<div style="font-size:22px;font-weight:800;color:#FF6B1A">STATEMENT</div>
<div style="margin-top:4px">As on: ${new Date().toLocaleDateString('en-IN')}</div>
</div>
</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px">
<div style="background:#f9fafb;border-radius:10px;padding:14px;border:1px solid #e5e7eb">
<div style="font-size:11px;color:#9ca3af;text-transform:uppercase;margin-bottom:6px">Party Details</div>
<div style="font-size:16px;font-weight:700">${party.name}</div>
<div style="font-size:13px;color:#6b7280">${party.city} · ${party.phone || ''}</div>
${party.gstin ? `<div style="font-size:12px;color:#6b7280">GSTIN: ${party.gstin}</div>` : ''}
</div>
<div style="background:${party.balanceType === 'to_receive' ? '#DCFCE7' : '#FEE2E2'};border-radius:10px;padding:14px;border:1px solid ${party.balanceType === 'to_receive' ? '#86EFAC' : '#FCA5A5'}">
<div style="font-size:11px;color:#6b7280;text-transform:uppercase;margin-bottom:6px">${party.balanceType === 'to_receive' ? 'Outstanding (To Receive)' : 'Payable (To Pay)'}</div>
<div style="font-size:28px;font-weight:800;color:${party.balanceType === 'to_receive' ? '#16A34A' : '#DC2626'}">${fmtFull(party.balance)}</div>
</div>
</div>
<table>
<thead><tr><th>Date</th><th>Description</th><th style="text-align:right">Credit</th><th style="text-align:right">Debit</th><th style="text-align:right">Balance</th></tr></thead>
<tbody>${rows || '<tr><td colspan="5" style="text-align:center;padding:20px;color:#9ca3af">No transactions found</td></tr>'}</tbody>
</table>
<div style="margin-top:24px;text-align:center;font-size:11px;color:#d1d5db">Generated by HisaabPro · ${new Date().toLocaleString('en-IN')}</div>
</div></body></html>`
}

export default function PartyDetailScreen({ party, onBack }) {
  const { transactions, addTransaction, deleteTransaction, language, currentUser, business, parties, editParty } = useApp()
  const hi = language === 'hi'
  const [showAddModal, setShowAddModal] = useState(false)
  const [editTxn, setEditTxn] = useState(null)

  // Get latest party data (balance may have changed)
  const latestParty = parties.find(p => p.id === party.id) || party

  const partyTxns = transactions
    .filter(t => t.partyId === party.id)
    .sort((a, b) => new Date(b.date) - new Date(a.date))

  const handleWhatsApp = () => {
    const msg = encodeURIComponent(
      `Dear ${latestParty.name},\n\nYour current balance with *${business?.name || currentUser?.name}* is *${fmtFull(latestParty.balance)}* (${latestParty.balanceType === 'to_receive' ? 'to pay us' : 'we owe you'}).\n\nKindly arrange payment at your earliest convenience.\n\nThank you 🙏\n${business?.name}`
    )
    window.open(`https://wa.me/91${latestParty.phone}?text=${msg}`, '_blank')
  }

  const handleStatement = () => {
    const html = generateStatementHTML(latestParty, transactions, business)
    const win = window.open('', '_blank', 'width=900,height=700')
    win.document.write(html)
    win.document.close()
  }

  const handleShare = async () => {
    const text = `*Account Statement - ${latestParty.name}*\n\nBusiness: ${business?.name}\nDate: ${new Date().toLocaleDateString('en-IN')}\n\nOutstanding Balance: *${fmtFull(latestParty.balance)}* (${latestParty.balanceType === 'to_receive' ? 'To Receive' : 'To Pay'})\n\nTotal Transactions: ${partyTxns.length}\n\n_Generated by HisaabPro_`
    if (navigator.share) {
      try {
        await navigator.share({ title: `Statement - ${latestParty.name}`, text })
      } catch (e) {}
    } else {
      // Fallback — copy to clipboard
      navigator.clipboard?.writeText(text)
      alert('Statement copied to clipboard! Paste it anywhere.')
    }
  }

  const handleDeleteTxn = (txnId) => {
    if (window.confirm('Delete this transaction?')) deleteTransaction(txnId)
  }

  const typeLabels = { sale: 'Invoice Raised', purchase: 'Purchase Invoice', receipt: 'Payment Received ✓', payment: 'Payment Made ✓' }

  return (
    <div style={{ paddingBottom: 80 }}>
      {/* Header */}
      <div style={{ background: 'var(--brand)', padding: '20px 16px 24px', borderRadius: '0 0 24px 24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
          <button onClick={onBack} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: 10, width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: 'white' }}>
            <ArrowLeft size={18} />
          </button>
          <div style={{ flex: 1 }}>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 700, color: 'white', marginBottom: 2 }}>{latestParty.name}</h2>
            <p style={{ color: 'rgba(255,255,255,0.6)', fontSize: 13 }}>{latestParty.city} {latestParty.phone ? `· ${latestParty.phone}` : ''}</p>
          </div>
          {latestParty.phone && (
            <a href={`tel:+91${latestParty.phone}`} style={{ background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: 10, width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', textDecoration: 'none' }}>
              <Phone size={16} />
            </a>
          )}
        </div>

        {/* Balance */}
        <div style={{ background: 'rgba(255,255,255,0.12)', borderRadius: 18, padding: '18px 20px', border: '1px solid rgba(255,255,255,0.2)', textAlign: 'center', marginBottom: 14 }}>
          <p style={{ color: 'rgba(255,255,255,0.65)', fontSize: 13, marginBottom: 8 }}>
            {latestParty.balanceType === 'to_receive' ? (hi ? 'आपको मिलना है' : 'You will receive') : (hi ? 'आपको देना है' : 'You will pay')}
          </p>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 36, fontWeight: 800, color: latestParty.balanceType === 'to_receive' ? '#4ADE80' : '#F87171' }}>
            {fmtFull(latestParty.balance)}
          </div>
          {latestParty.balance === 0 && <div style={{ color: '#4ADE80', fontSize: 14, fontWeight: 600, marginTop: 4 }}>✓ Settled</div>}
        </div>

        {/* Party Intelligence */}
        {partyTxns.length > 0 && (() => {
          const payments = partyTxns.filter(t => t.type === 'receipt' || t.type === 'payment')
          const lastPayment = payments[0]
          const daysSincePayment = lastPayment ? Math.floor((new Date() - new Date(lastPayment.date)) / (1000*60*60*24)) : null
          const avgBalance = partyTxns.length > 0 ? Math.round(partyTxns.reduce((s,t) => s + (t.balanceAfter||0), 0) / partyTxns.length) : 0
          const riskScore = latestParty.balance > 100000 ? 'High' : latestParty.balance > 30000 ? 'Medium' : 'Low'
          const riskColor = riskScore === 'High' ? 'var(--red)' : riskScore === 'Medium' ? 'var(--amber)' : 'var(--green)'
          const riskBg = riskScore === 'High' ? 'var(--red-light)' : riskScore === 'Medium' ? 'var(--amber-light)' : 'var(--green-light)'
          return (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 8, marginBottom: 10 }}>
              <div style={{ background: 'rgba(255,255,255,0.12)', borderRadius: 12, padding: '10px 8px', textAlign: 'center', border: '1px solid rgba(255,255,255,0.2)' }}>
                <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: 9, textTransform: 'uppercase', marginBottom: 4 }}>Last Payment</div>
                <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, color: 'white', fontSize: 14 }}>{daysSincePayment !== null ? `${daysSincePayment}d ago` : 'None'}</div>
              </div>
              <div style={{ background: 'rgba(255,255,255,0.12)', borderRadius: 12, padding: '10px 8px', textAlign: 'center', border: '1px solid rgba(255,255,255,0.2)' }}>
                <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: 9, textTransform: 'uppercase', marginBottom: 4 }}>Transactions</div>
                <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, color: 'white', fontSize: 14 }}>{partyTxns.length}</div>
              </div>
              <div style={{ background: riskBg, borderRadius: 12, padding: '10px 8px', textAlign: 'center', border: `1px solid ${riskColor}40` }}>
                <div style={{ color: riskColor, fontSize: 9, textTransform: 'uppercase', marginBottom: 4, opacity: 0.8 }}>Risk Score</div>
                <div style={{ fontFamily: 'var(--font-display)', fontWeight: 800, color: riskColor, fontSize: 14 }}>{riskScore}</div>
              </div>
            </div>
          )
        })()}

        {/* Action Buttons */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
          {[
            { label: hi ? 'WhatsApp' : 'WhatsApp', bg: '#25D366', icon: '📱', action: handleWhatsApp, show: !!latestParty.phone },
            { label: hi ? 'स्टेटमेंट' : 'Statement', bg: 'rgba(255,255,255,0.15)', icon: '📄', action: handleStatement, show: true },
            { label: hi ? 'शेयर' : 'Share', bg: 'rgba(255,255,255,0.15)', icon: '↗️', action: handleShare, show: true },
          ].filter(b => b.show).map((btn, i) => (
            <button key={i} onClick={btn.action} style={{ padding: '10px 6px', borderRadius: 12, border: '1px solid rgba(255,255,255,0.2)', cursor: 'pointer', background: btn.bg, color: 'white', fontWeight: 700, fontSize: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 4 }}>
              <span>{btn.icon}</span> {btn.label}
            </button>
          ))}
        </div>
      </div>

      {/* Transactions */}
      <div style={{ padding: '16px 16px 0' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' }}>
            {hi ? 'लेन-देन इतिहास' : 'Transaction History'} ({partyTxns.length})
          </h3>
        </div>

        {partyTxns.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 20px', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 40, marginBottom: 12 }}>📋</div>
            <p style={{ fontWeight: 600 }}>{hi ? 'कोई लेन-देन नहीं' : 'No transactions yet'}</p>
            <p style={{ fontSize: 13, marginTop: 4 }}>Tap + to add first entry</p>
          </div>
        ) : (
          <div className="card" style={{ overflow: 'hidden' }}>
            {partyTxns.map((t, i) => {
              const isIncoming = t.type === 'sale' || t.type === 'receipt'
              return (
                <div key={t.id} style={{ padding: '12px 14px', borderBottom: i < partyTxns.length - 1 ? '1px solid var(--border-light)' : 'none', display: 'flex', alignItems: 'center', gap: 10 }}>
                  <div style={{ width: 36, height: 36, borderRadius: 10, flexShrink: 0, background: isIncoming ? 'var(--green-light)' : 'var(--red-light)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    {isIncoming ? <TrendingUp size={15} color="var(--green)" /> : <TrendingDown size={15} color="var(--red)" />}
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <div style={{ fontWeight: 600, fontSize: 13 }}>{typeLabels[t.type] || t.type}</div>
                      <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 14, color: isIncoming ? 'var(--green)' : 'var(--red)', flexShrink: 0, marginLeft: 8 }}>
                        {isIncoming ? '+' : '-'}{fmtFull(t.amount)}
                      </div>
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 2 }}>
                      <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{t.note || '—'} {t.billNo ? `· ${t.billNo}` : ''}</span>
                      <span style={{ fontSize: 11, color: 'var(--text-muted)', flexShrink: 0 }}>{t.date}</span>
                    </div>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 1 }}>
                      Balance: <strong>{fmtFull(t.balanceAfter || 0)}</strong>
                    </div>
                  </div>
                  {/* Delete transaction */}
                  <button onClick={() => handleDeleteTxn(t.id)} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px', borderRadius: 6, color: 'var(--text-muted)', flexShrink: 0 }}
                    onMouseEnter={e => e.currentTarget.style.color = 'var(--red)'}
                    onMouseLeave={e => e.currentTarget.style.color = 'var(--text-muted)'}>
                    <Trash2 size={14} />
                  </button>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* FAB */}
      <button onClick={() => setShowAddModal(true)} style={{ position: 'fixed', bottom: 88, right: 20, width: 56, height: 56, borderRadius: '50%', background: 'linear-gradient(135deg, var(--saffron), #FF8C42)', border: 'none', cursor: 'pointer', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow-saffron)', zIndex: 50 }}>
        <Plus size={24} />
      </button>

      {showAddModal && <AddTransactionModal party={latestParty} onClose={() => setShowAddModal(false)} />}
    </div>
  )
}

function AddTransactionModal({ party, onClose }) {
  const { addTransaction, language } = useApp()
  const hi = language === 'hi'
  const isCustomer = party.type === 'customer' || party.type === 'both'
  const [form, setForm] = useState({ type: isCustomer ? 'sale' : 'purchase', amount: '', note: '', billNo: '', date: new Date().toISOString().split('T')[0] })
  const [error, setError] = useState('')

  const typeOptions = isCustomer
    ? [{ v: 'sale', l: 'Sale (Credit)', lhi: 'बिक्री (उधार)' }, { v: 'receipt', l: 'Payment Received', lhi: 'भुगतान मिला' }]
    : [{ v: 'purchase', l: 'Purchase (Credit)', lhi: 'खरीद (उधार)' }, { v: 'payment', l: 'Payment Made', lhi: 'भुगतान किया' }]

  const handleSave = () => {
    if (!form.amount || Number(form.amount) <= 0) { setError('Please enter a valid amount'); return }
    const currentBalance = party.balance
    let newBalance = currentBalance
    if (form.type === 'sale') newBalance += Number(form.amount)
    if (form.type === 'receipt') newBalance = Math.max(0, currentBalance - Number(form.amount))
    if (form.type === 'purchase') newBalance += Number(form.amount)
    if (form.type === 'payment') newBalance = Math.max(0, currentBalance - Number(form.amount))
    addTransaction({ partyId: party.id, type: form.type, amount: Number(form.amount), balanceAfter: newBalance, note: form.note, billNo: form.billNo, date: form.date })
    onClose()
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', zIndex: 200, display: 'flex', alignItems: 'flex-end', backdropFilter: 'blur(4px)' }}
      onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="card slide-up" style={{ width: '100%', borderRadius: '24px 24px 0 0', padding: '24px 20px 40px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
          <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 20, fontWeight: 700, color: 'var(--indigo)' }}>{hi ? 'एंट्री जोड़ें' : 'Add Entry'}</h3>
          <button onClick={onClose} style={{ background: 'var(--bg)', border: 'none', borderRadius: 10, width: 32, height: 32, cursor: 'pointer', fontSize: 18 }}>✕</button>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: 13, marginBottom: 20 }}>{party.name}</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ display: 'flex', gap: 10 }}>
            {typeOptions.map(o => (
              <button key={o.v} onClick={() => setForm(f => ({ ...f, type: o.v }))} style={{ flex: 1, padding: '12px 8px', borderRadius: 14, fontSize: 13, fontWeight: 700, cursor: 'pointer', border: form.type === o.v ? 'none' : '1.5px solid var(--border)', background: form.type === o.v ? (o.v === 'sale' || o.v === 'purchase') ? 'linear-gradient(135deg, var(--saffron), #FF8C42)' : 'var(--green)' : 'white', color: form.type === o.v ? 'white' : 'var(--text-secondary)' }}>
                {hi ? o.lhi : o.l}
              </button>
            ))}
          </div>
          <div>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 6 }}>{hi ? 'राशि *' : 'Amount *'}</label>
            <div style={{ position: 'relative' }}>
              <span style={{ position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)', fontFamily: 'var(--font-display)', fontWeight: 700, color: 'var(--text-secondary)', fontSize: 18 }}>₹</span>
              <input className="input-field" style={{ paddingLeft: 32, fontSize: 22, fontFamily: 'var(--font-display)', fontWeight: 700 }} placeholder="0" type="number" value={form.amount} onChange={e => { setForm(f => ({ ...f, amount: e.target.value })); setError('') }} autoFocus />
            </div>
          </div>
          <div>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 6 }}>{hi ? 'तारीख' : 'Date'}</label>
            <input className="input-field" type="date" value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))} />
          </div>
          <div>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 6 }}>{hi ? 'विवरण' : 'Note (optional)'}</label>
            <input className="input-field" placeholder={hi ? 'जैसे: बासमती चावल 50 बैग' : 'e.g. Basmati rice 50 bags'} value={form.note} onChange={e => setForm(f => ({ ...f, note: e.target.value }))} />
          </div>
          <div>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 6 }}>{hi ? 'बिल नंबर' : 'Bill No. (optional)'}</label>
            <input className="input-field" placeholder="INV-2026-001" value={form.billNo} onChange={e => setForm(f => ({ ...f, billNo: e.target.value }))} />
          </div>
          {error && <p style={{ color: 'var(--red)', fontSize: 13 }}>{error}</p>}
          <button className="btn-primary" style={{ width: '100%' }} onClick={handleSave}>{hi ? 'एंट्री सेव करें ✓' : 'Save Entry ✓'}</button>
        </div>
      </div>
    </div>
  )
}
